#!/bin/sh
rm -rf webos-libs-install.sh
touch webos-libs-install.sh
echo "#!/bin/sh" > webos-libs-install.sh
echo "FSO_ROOTFS=\$1" >> webos-libs-install.sh
echo "" >> webos-libs-install.sh
echo "FILES=\" \ " >> webos-libs-install.sh
for f in `find staging/armv7 -type f -print` ; do 
	echo -n `echo $f | sed 's/staging\/armv7//'` >> webos-libs-install.sh
	echo " \\ " >> webos-libs-install.sh
done
echo "\"" >> webos-libs-install.sh
echo "" >> webos-libs-install.sh
echo "for file in \$FILES ; do" >> webos-libs-install.sh
echo " if [ ! \$file == \"\\\\\" ] ; then " >> webos-libs-install.sh
echo "  new_file=\`echo \$file | sed 's/^\\///'\`" >> webos-libs-install.sh
echo "  new_path=\`dirname \$file | sed 's/^\\///'\`" >> webos-libs-install.sh
echo "  echo \"mkdir -p \$FSO_ROOTFS/\$new_path\"" >> webos-libs-install.sh
echo "  echo \"cp -pR \$file \$FSO_ROOTFS/\$new_file\"" >> webos-libs-install.sh
echo " fi" >> webos-libs-install.sh
echo "done" >> webos-libs-install.sh
