/* main.c generated by valac 0.11.6.36-cd9d-dirty, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>




void _vala_main (void);


void _vala_main (void) {
}


int main (int argc, char ** argv) {
	g_type_init ();
	_vala_main ();
	return 0;
}



